Repository CSW-Study-Group/BOARD, pull requests merged in 2023-07, with the labels that each got.

#17 Feat: Feature attendance
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/src/controllers/user.js
  BackEnd/src/functions/common.js
  BackEnd/src/functions/winston.js
  BackEnd/src/middleware/validator.js
  BackEnd/src/models/attendance.js
  BackEnd/src/models/index.js
  BackEnd/src/models/user.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/user.js
  BackEnd/src/test/user.test.js
  FrontEnd/public/css/calendar.css
  FrontEnd/public/js/index.js
  FrontEnd/public/js/user/attendance.js
  FrontEnd/public/js/user/profile.js
  FrontEnd/views/partials/nav.ejs
  FrontEnd/views/user/attendance.ejs
  FrontEnd/views/user/profile.ejs
Labels: ♻ Refactor, 🛠 Feat, ⚙ Setting

#28 Feature ip block
  BackEnd/loaders/blockedIp.js
  BackEnd/server.js
  BackEnd/src/models/blockedIp.js
  BackEnd/src/models/index.js
  BackEnd/src/services/blockedIp.js
Labels: 🛠 Feat

#29 Feature pw change
  BackEnd/src/controllers/user.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/user.js
  BackEnd/src/test/user.test.js
  FrontEnd/public/js/user/password.js
  FrontEnd/views/user/password.ejs
  FrontEnd/views/user/profile.ejs
Labels: 🛠 Feat

#30 1.6.1 버전 배포
  BackEnd/CHANGELOG.md
  BackEnd/loaders/blockedIp.js
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/server.js
  BackEnd/src/controllers/user.js
  BackEnd/src/models/blockedIp.js
  BackEnd/src/models/index.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/blockedIp.js
  BackEnd/src/services/user.js
  BackEnd/src/test/user.test.js
  FrontEnd/public/js/user/password.js
  FrontEnd/views/user/password.ejs
  FrontEnd/views/user/profile.ejs
Labels: 🌍 Release, 📈 Update
