Repository CSW-Study-Group/BOARD, pull requests merged in 2023-06, with the labels that each got.

#16 Feat: Feature log
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/src/controllers/board.js
  BackEnd/src/controllers/user.js
  BackEnd/src/functions/responseStatus.js
  BackEnd/src/functions/winston.js
  BackEnd/src/middleware/multer.js
  BackEnd/src/middleware/validator.js
  BackEnd/src/routes/board.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/board.js
  BackEnd/src/services/user.js
  FrontEnd/public/js/user/profile.js
  FrontEnd/public/js/user/register.js
  FrontEnd/views/user/login.ejs
  FrontEnd/views/user/register.ejs
Labels: ♻ Refactor, 🛠 Feat

#24 Merge 1.5.0v 배포
  BackEnd/src/controllers/board.js
  BackEnd/src/models/comment.js
  BackEnd/src/models/index.js
  BackEnd/src/models/post.js
  BackEnd/src/models/user.js
  BackEnd/src/routes/board.js
  BackEnd/src/services/board.js
  FrontEnd/public/css/master.css
  FrontEnd/public/js/post/read.js
  FrontEnd/views/home/welcome.ejs
  FrontEnd/views/post/read.ejs
Labels: 🌍 Release

#25 Feature branch 리팩토링 작업
  BackEnd/CHANGELOG.md
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/src/controllers/board.js
  BackEnd/src/controllers/user.js
  BackEnd/src/routes/board.js
  BackEnd/src/services/board.js
  FrontEnd/public/js/post/read.js
Labels: ♻ Refactor, 📈 Update

#26 Feature TDD Merge
  BackEnd/.gitignore
  BackEnd/loaders/module.js
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/server.js
  BackEnd/src/controllers/board.js
  BackEnd/src/controllers/home.js
  BackEnd/src/controllers/user.js
  BackEnd/src/functions/query.js
  BackEnd/src/functions/responseStatus.js
  BackEnd/src/functions/signJWT.js
  BackEnd/src/functions/winston.js
  BackEnd/src/middleware/multer.js
  BackEnd/src/middleware/verifyJWT.js
  BackEnd/src/models/comment.js
  BackEnd/src/models/index.js
  BackEnd/src/models/log.js
  BackEnd/src/models/post.js
  BackEnd/src/models/user.js
  BackEnd/src/routes/board.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/board.js
  BackEnd/src/services/user.js
  BackEnd/src/test/board.test.js
  BackEnd/src/test/user.test.js
  BackEnd/src/utils/connect.js
  FrontEnd/public/js/index.js
  FrontEnd/public/js/post/create.js
  FrontEnd/public/js/post/read.js
  FrontEnd/public/js/post/update.js
  FrontEnd/public/js/user/login.js
  FrontEnd/public/js/user/profile.js
  FrontEnd/public/js/user/register.js
  FrontEnd/views/post/read.ejs
Labels: ♻ Refactor, 🛠 Feat, ⚙ Setting
