Repository CSW-Study-Group/BOARD, pull requests merged in 2023-05, with the labels that each got.

#18 발견된 이슈 해결
  BackEnd/src/controllers/board.js
  BackEnd/src/models/log.js
  FrontEnd/public/js/post/update.js
  FrontEnd/public/js/user/profile.js
  FrontEnd/public/js/user/register.js
  FrontEnd/views/post/index.ejs
Labels: ⚠ Bug, ♻ Refactor

#19 Develop 업데이트
  BackEnd/src/controllers/board.js
  BackEnd/src/models/log.js
  FrontEnd/public/js/post/update.js
  FrontEnd/public/js/user/profile.js
  FrontEnd/public/js/user/register.js
  FrontEnd/views/post/index.ejs
Labels: 📈 Update

#20 1.3.2 배포 (버전 업데이트)
  BackEnd/src/controllers/board.js
  BackEnd/src/models/log.js
  FrontEnd/public/js/post/update.js
  FrontEnd/public/js/user/profile.js
  FrontEnd/public/js/user/register.js
  FrontEnd/views/post/index.ejs
Labels: 🌍 Release

#21 Refactor: user refactor
  BackEnd/src/controllers/user.js
  BackEnd/src/middleware/multer.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/user.js
Labels: ♻ Refactor
